### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by schiyu** [tuya/tuya-ui-bizbundle-android-demo#2]
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class androidx.annotation.InspectableProperty found in modules annotation-1.1.0.jar (androidx.annotation:annotation:1.1.0) and jetified-tuyasmart-hardware-3.20.0-beta1-runtime.jar (com.tuya.smart:tuyasmart-hardware:3.20.0-beta1)
  Duplicate class androidx.annotation.InspectableProperty$ValueType found in modules annotation-1.1.0.jar (androidx.annotation:annotation:1.1.0) and jetified-tuyasmart-hardware-3.20.0-beta1-runtime.jar (com.tuya.smart:tuyasmart-hardware:3.20.0-beta1)
  Duplicate class androidx.annotation.Keep found in modules annotation-1.1.0.jar (androidx.annotation:annotation:1.1.0) and jetified-tuyasmart-hardware-3.20.0-beta1-runtime.jar (com.tuya.smart:tuyasmart-hardware:3.20.0-beta1)
  Duplicate class androidx.annotation.RestrictTo found in modules annotation-1.1.0.jar (androidx.annotation:annotation:1.1.0) and jetified-tuyasmart-hardware-3.20.0-beta1-runtime.jar (com.tuya.smart:tuyasmart-hardware:3.20.0-beta1)
  Duplicate class androidx.annotation.RestrictTo$Scope found in modules annotation-1.1.0.jar (androidx.annotation:annotation:1.1.0) and jetified-tuyasmart-hardware-3.20.0-beta1-runtime.jar (com.tuya.smart:tuyasmart-hardware:3.20.0-beta1)
  Duplicate class com.facebook.soloader.MinElf found in modules jetified-soloader-0.8.2-runtime.jar (com.facebook.soloader:soloader:0.8.2) and jetified-tuyasmart-hardware-3.20.0-beta1-runtime.jar (com.tuya.smart:tuyasmart-hardware:3.20.0-beta1)
  Duplicate class com.facebook.soloader.MinElf$ElfError found in modules jetified-soloader-0.8.2-runtime.jar (com.facebook.soloader:soloader:0.8.2) and jetified-tuyasmart-hardware-3.20.0-beta1-runtime.jar (com.tuya.smart:tuyasmart-hardware:3.20.0-beta1)
  Duplicate class com.facebook.soloader.MinElf$ISA found in modules jetified-soloader-0.8.2-runtime.jar (com.facebook.soloader:soloader:0.8.2) and jetified-tuyasmart-hardware-3.20.0-beta1-runtime.jar (com.tuya.smart:tuyasmart-hardware:3.20.0-beta1)
  Duplicate class com.facebook.soloader.SoLoader found in modules jetified-soloader-0.8.2-runtime.jar (com.facebook.soloader:soloader:0.8.2) and jetified-tuyasmart-hardware-3.20.0-beta1-runtime.jar (com.tuya.smart:tuyasmart-hardware:3.20.0-beta1)
  Duplicate class com.facebook.soloader.SoLoader$WrongAbiError found in modules jetified-soloader-0.8.2-runtime.jar (com.facebook.soloader:soloader:0.8.2) and jetified-tuyasmart-hardware-3.20.0-beta1-runtime.jar (com.tuya.smart:tuyasmart-hardware:3.20.0-beta1)

**Comment by AhmedAbouelkher** [comment]
How did you fix this issssue?
