### ISSUE TITLE
Bug: QRCode Image Color Inverted tuyasmart-bizbundle-device_activator on Android Dark theme (when it is enabled)  

### ISSUE THREAD

**Issue by tanshuai** [tuya/tuya-ui-bizbundle-android-demo#28]
My project used ```com.tuya.smart:tuyasmart-bizbundle-device_activator:3.22.0-9``` & ```com.tuya.smart:tuyasmart:3.24.1``` APIs.

QRCode Image Color of Device Activator will be Inverted when Dark them is enabled by Android System. 

**Incorrect QRCode with Inverted Color when Dark theme is enabled**
![Screenshot_1626439879](https://user-images.githubusercontent.com/3947852/125951025-4f2cb2e0-bce0-4139-878c-8254961d7f12.png)

![Screenshot_1626439870](https://user-images.githubusercontent.com/3947852/125951053-566daeef-e24a-4e85-95e1-56458a803828.png)

**Comment by Innocencellh** [comment]
Pls try use a real device camera to scan the incorrect QR Code (Inverted Color).

**Comment by Innocencellh** [comment]
@tanshuai 
Thank u for your feedback ，we do not support this feature now . You can refer this passage to change the  backgroud not black color . https://developer.tuya.com/en/docs/app-development/android-colors-theme?id=Kapl9ox0ysvgs.

**Comment by tanshuai** [comment]
@Innocencellh :

Thank you for you reply.

The dark theme is the current mainstream and it should be supported by default.

We expect you to support this feature as soon as possible.

**Comment by tanshuai** [comment]
![fix-qr-code-bug](https://user-images.githubusercontent.com/3947852/130221626-37b8af54-20fc-493c-bc65-9ea09268e183.jpeg)

This problem has been fixed by a workaround. 

Please consider the official fix as it is  very simple with few lines of code.
