### ISSUE TITLE
Project increase CPU utilization of System when open in android studio

### ISSUE THREAD

**Issue by saurabhsinghapps** [tuya/tuya-ui-bizbundle-android-demo#41]
Project increase CPU utilization of System when open in android studio. 
CPU Utilization going 100% when i wright anything or scroll the project.  
Please suggest here how i can resolve this issue. This is happening for this specific project. 
I attached my system configuration.

![InkedCapture_LI](https://user-images.githubusercontent.com/6761607/165670182-a1220288-229b-4a0a-851f-6f0b8930e8e1.jpg)

**Comment by linhuiluo** [comment]
@saurabhsinghapps Sorry, we currently have no better optimization for this project. We can only recommend you to keep this window.
