### ISSUE TITLE
Bizbundle new update ?

### ISSUE THREAD

**Issue by Ezaldeen99** [tuya/tuya-ui-bizbundle-android-demo#44]
Hello we just want to ask about the difference between bizbundle version number `4.2.0-22` and your published Tuya app difference. 

below you can see a picture for the same device from biz bundle `4.2.0-22` 

![WhatsApp Image 2023-02-28 at 10 12 31 AM](https://user-images.githubusercontent.com/30810111/224472432-e2b3bd09-8257-4ac0-a3c6-25d1e5f2843e.jpeg)

and adding the same device in the Tuya app, gives more options and features.

![WhatsApp Image 2023-02-28 at 10 12 30 AM](https://user-images.githubusercontent.com/30810111/224472454-c6de47af-0002-4af3-83cc-d567c950f392.jpeg)

**we specifically needed the two gateway switch feature which we noticed that is missing from the latest biz bundle update.**

our app versions are

        tuya_version = '4.0.2'
        bizbundle_version = '4.2.0-22'

would you please help us to know if there are any new updates for the biz bundle library or we need to do something from our side to enable such features in the device control panels

**Comment by linhuiluo** [comment]
@Ezaldeen99 Sorry, our current UIBizbUndle is only partially open.
