### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by bingely** [tuya/tuya-ui-bizbundle-android-demo#50]
Multiple build operations failed.
    Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.thingclips.smart:thingsmart-login-plug-api:4.5.0-rc.2, variantName=null, artifactFile=C:\Users\user\.gradle\caches\modules-2\files-2.1\com.thingclips.smart\thingsmart-login-plug-api\4.5.0-rc.2\a65a49b386b2270f097ec54e10559262e63297b7\thingsmart-login-plug-api-4.5.0-rc.2.aar, extractedFolder=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=E:\xhrj_project\TuYa\tuya-ui-bizbundle-android-demo}, mavenCoordinatesCache=com.android.build.gradle.internal.ide.dependencies.MavenCoordinatesCacheBuildService$Inject@25c461cc)
    Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.thingclips.smart:thingsmart-login-plug-api:4.5.0-rc.2, variantName=null, artifactFile=C:\Users\user\.gradle\caches\modules-2\files-2.1\com.thingclips.smart\thingsmart-login-plug-api\4.5.0-rc.2\a65a49b386b2270f097ec54e10559262e63297b7\thingsmart-login-plug-api-4.5.0-rc.2.aar, extractedFolder=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=E:\xhrj_project\TuYa\tuya-ui-bizbundle-android-demo}, mavenCoordinatesCache=com.android.build.gradle.internal.ide.dependencies.MavenCoordinatesCacheBuildService$Inject@25c461cc)
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.thingclips.smart:thingsmart-login-plug-api:4.5.0-rc.2, variantName=null, artifactFile=C:\Users\user\.gradle\caches\modules-2\files-2.1\com.thingclips.smart\thingsmart-login-plug-api\4.5.0-rc.2\a65a49b386b2270f097ec54e10559262e63297b7\thingsmart-login-plug-api-4.5.0-rc.2.aar, extractedFolder=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=E:\xhrj_project\TuYa\tuya-ui-bizbundle-android-demo}, mavenCoordinatesCache=com.android.build.gradle.internal.ide.dependencies.MavenCoordinatesCacheBuildService$Inject@25c461cc)

**Comment by MRwangqi** [comment]
@bingely 
For windows system, you need to upgrade the dependent version com.thingclips.smart:thingsmart-login-plug-api:4.5.0-rc.3
