### ISSUE TITLE
No implementation found for java.lang.Object com.thingclips ....

### ISSUE THREAD

**Issue by Proxy13** [tuya/tuya-ui-bizbundle-android-demo#52]
[log.txt](https://github.com/tuya/tuya-ui-bizbundle-android-demo/files/12857953/log.txt)

**Comment by taojingGino** [comment]
https://developer.tuya.com/cn/docs/app-development/integrated?id=Ka69nt96cw0uj#title-5-%E7%AC%AC%E4%B8%89%E6%AD%A5%EF%BC%9A%E9%9B%86%E6%88%90%E5%AE%89%E5%85%A8%E7%BB%84%E4%BB%B6

@Proxy13 You need to follow this step to integrate the SDK
